services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    environment:
      APP_HOST: planning-myelogrammes_web_1
      APP_PORT: 3000

  web:
    image: planning-myelogrammes:local
    pull_policy: never
    restart: on-failure
    environment:
      PORT: 3000
      DATA_DIR: /data
    volumes:
      - ${APP_DATA_DIR}/data:/data
